### ISSUE TITLE
The searchBar .wrap has absolute

### ISSUE THREAD

**Issue by 00258219** [HeyChobe/bombastic-ui#33]
### Prerequisites

- [X] I have [searched](https://github.com/HeyChobe/bombastic-ui/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/HeyChobe/bombastic-ui/blob/feature/contributin-guide/.github/CONTRIBUTING.md)

### Describe the issue

SearchBar componente display on absolute, so in order to show correctly you have to set the position: relative to his father.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

the latest

**Comment by HeyChobe** [comment]
#34
